### PR TITLE
Sp 4818 update varsome api client to use commitizen

### PR DESCRIPTION
**Pull request by thasteris**

### CODE REVIEW

**Comment by n-zervos** [comment]
Great work @thasteris !

General question, wouldn't it be worth it to also add poetry to the `pyproject.toml` file so that poetry can handle dependency management? @kchatzikok Your thoughts?

**Comment by thasteris** [comment]
Thanks @n-zervos , for your input, however in this phase in development we won't be implementing poetry, this will be moved to a later phase. @kchatzikok Do you agree?

**Review by n-zervos — APPROVED** [review]

**Review by bsantor — APPROVED** [review]
Great job @thasteris! 👍🏼

**Review by kchatzikok — APPROVED** [review]

**Comment by kchatzikok** [comment]
@n-zervos @thasteris it's ok like that for now. We might consider adding poetry for dependency management in the future

**Pull request merged**
